# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/MyS_workspace/LedController/Sintesis/LedController/LedController.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0.xci
# IP: The module: 'System_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/MyS_workspace/LedController/Sintesis/LedController/LedController.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/MyS_workspace/LedController/Sintesis/LedController/LedController.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0.xci
# IP: The module: 'System_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/MyS_workspace/LedController/Sintesis/LedController/LedController.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
