# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/MyS_workspace/TPFinal/Fuentes/Implementacion/ArtyZ7_10.xdc

# Block Designs: bd/transceiver/transceiver.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver || ORIG_REF_NAME==transceiver} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_processing_system7_0_0/transceiver_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_processing_system7_0_0 || ORIG_REF_NAME==transceiver_processing_system7_0_0} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_axi_gpio_0_0/transceiver_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_axi_gpio_0_0 || ORIG_REF_NAME==transceiver_axi_gpio_0_0} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_ps7_0_axi_periph_0/transceiver_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_ps7_0_axi_periph_0 || ORIG_REF_NAME==transceiver_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_rst_ps7_0_100M_0/transceiver_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_rst_ps7_0_100M_0 || ORIG_REF_NAME==transceiver_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_Transmitter_IP_0_0/transceiver_Transmitter_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_Transmitter_IP_0_0 || ORIG_REF_NAME==transceiver_Transmitter_IP_0_0} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_Receiver_IP_0_0/transceiver_Receiver_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_Receiver_IP_0_0 || ORIG_REF_NAME==transceiver_Receiver_IP_0_0} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_xbar_0/transceiver_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_xbar_0 || ORIG_REF_NAME==transceiver_xbar_0} -quiet] -quiet

# IP: bd/transceiver/ip/transceiver_auto_pc_0/transceiver_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transceiver_auto_pc_0 || ORIG_REF_NAME==transceiver_auto_pc_0} -quiet] -quiet

# XDC: bd/transceiver/transceiver_ooc.xdc
